CREATE DATABASE ScuolaDb;
GO

USE ScuolaDb;
GO

-- CREAZIONE DELLA TABELLA STUDENTI
CREATE TABLE Studenti(
	StudenteId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nome NVARCHAR(50) NOT NULL,
	Cognome NVARCHAR(50) NOT NULL,
	Email NVARCHAR(150) UNIQUE NULL,
	CodiceFiscale CHAR(16) UNIQUE NOT NULL,
	DataNascita DATE NULL,
	Telefono NVARCHAR(20) UNIQUE NULL
);

-- CREAZIONE DELLA TABELLA CORSI
CREATE TABLE Corsi(
    -- Id del corso (auto incrementale)
    CorsoId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NomeCorso NVARCHAR(100) NOT NULL,
    DescrizioneCorso NVARCHAR(256) NULL,
    Crediti INT NULL,
    Durata INT NULL
);

-- CREAZIONE DELLA TABELLA DOCENTI
CREATE TABLE Docenti(
	DocenteId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nome NVARCHAR(50) NOT NULL,
	Cognome NVARCHAR(50) NOT NULL,
	Email NVARCHAR(150) UNIQUE NULL,
	Specializzazione NVARCHAR(100) NULL 
);


-- CREAZIONE DELLA TABELLA AULE
CREATE TABLE Aule(
	AulaId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NomeAula NVARCHAR(150) NOT NULL,
	Capacita INT NOT NULL
);

-- CHIAVE ESTERNA(FOREIGN KEY) DI UNA TABELLA 
-- CREAZIONE DELLA TABELLA ISCRIZIONE -> CORSI
CREATE TABLE Iscrizioni(
	IscrizioneId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	StudenteId INT NOT NULL, -- collegamento allo studente
	CorsoId INT NOT NULL, -- collegamento al corso
	DataIscrizione DATE NOT NULL,

	-- Vincoli di relazioni (Foreign key)
	FOREIGN KEY (StudenteId) REFERENCES Studenti(StudenteId),
	FOREIGN KEY (CorsoId) REFERENCES Corsi(CorsoId)
);


-- CREAZIONE DELLA TABELLA LEZIONI
CREATE TABLE Lezioni(
	LezioneId INT NOT NULL PRIMARY KEY IDENTITY(1,1),

	CorsoId INT NOT NULL,
	AulaId INT NULL,

	DataLezione DATE NOT NULL,
	OraInizio TIME, 
	OraFine TIME,

	-- RELAZIONI
	FOREIGN KEY (CorsoId) REFERENCES Corsi(CorsoId),
	FOREIGN KEY (AulaId) REFERENCES Aule(AulaId)
);



-- CREAZIONE DELLA TABELLA DocentiCorso
CREATE TABLE DocentiCorso(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	DocenteId INT NOT NULL,
	CorsoId INT NOT NULL,

	FOREIGN KEY (DocenteId) REFERENCES Docenti(DocenteId),
	FOREIGN KEY (CorsoId) REFERENCES Corsi(CorsoId)
);


